package utils

var (
	WordTypes = map[string]string{
		"substantiv": "",
		"adjectiv":   "",
		"verb":       "",
		"adverb":     "",
		"pronume":    "",
		"prepoziție": "",
		"conjuncție": "",
	}

	DefintionSources = map[string]string{
		"DEX '09":          "",
		"DOOM 3":           "",
		"Sinonime":         "",
		"DAS":              "",
		"Antonime":         "",
		"DEX '16":          "",
		"DEX '12":          "",
		"MDA2":             "",
		"DLR":              "",
		"DEXI":             "",
		"DEX '98":          "",
		"DEX '96":          "",
		"DEX-S":            "",
		"DEX '84":          "",
		"DEX '75":          "",
		"DLRLC":            "",
		"DLRM":             "",
		"MDA":              "",
		"DOOM 2":           "",
		"DOOM":             "",
		"DOR":              "",
		"Ortografic":       "",
		"DMLR":             "",
		"dexonline":        "",
		"DGS":              "",
		"Sinonime82":       "",
		"DN":               "",
		"MDN '08":          "",
		"MDN '00":          "",
		"DCR2":             "",
		"DLRC":             "",
		"DER":              "",
		"GER":              "",
		"DEI":              "",
		"GAER":             "",
		"NODEX":            "",
		"DLRLV":            "",
		"DAR":              "",
		"DSL":              "",
		"Mitologic":        "",
		"Șăineanu, ed. VI": "",
		"Scriban":          "",
		"DGL":              "",
		"DGE":              "",
		"Petro-Sedim":      "",
		"GTA":              "",
		"DTM":              "",
		"D Religios":       "",
		"Argou":            "",
		"DRAM 2015":        "",
		"DRAM":             "",
		"DE":               "",
		"DTL":              "",
		"DMG":              "",
		"Onomastic":        "",
		"CADE":             "",
		"DifSem":           "",
		"Neoficial":        "",
		"DFL":              "",
		"DLRA":             "",
		"DETS":             "",
		"DFS":              "",
		"DGSSL":            "",
		"DAN":              "",
		"Legislație":       "",
		"psi":              "",
		"MDO":              "",
		"DEX-școlar":       "",
		"IVO-III":          "",
		"MEO":              "",
		"DIN":              "",
		"MDTL":             "",
		"CECC":             "",
		"DRAM 2021":        "",
	}
)
